# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: grafana-ingress
#   namespace: default
#   annotations:
#     # kubernetes.io/ingress.class: "alb"
#     alb.ingress.kubernetes.io/scheme: "internet-facing"
#     alb.ingress.kubernetes.io/target-type: ip
# spec:
#   ingressClassName: alb
#   rules:
#     - host: grafana.temedia.dev # Replace with your desired domain
#       http:
#         paths:
#           - path: /
#             pathType: Prefix
#             backend:
#               service:
#                 name: prometheus-grafana
#                 port:
#                   number: 80
# helm installation for kube prometheus

# helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
# helm repo update
# helm install prometheus prometheus-community/kube-prometheus-stack

---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-grafana-loadbalancer
  namespace: kube-prometheus-stack
spec:
  selector:
    app: prometheus-grafana
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
